server:
  port: 8080
  context-path: /black

spring:
  datasource:
    url: jdbc:mysql://localhost/quickstart?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: fuyongde
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.126.com
    username: fuyongde@126.com
    password: de2441009fu
    default-encoding: UTF-8

logging:
  config: classpath:logback-spring.xml
