server:
  port: 8080
  context-path: /black

spring:
  datasource:
    url: jdbc:mysql://localhost/quickstart?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: fuyongde
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.126.com
    username: fuyongde@126.com
    password: de2441009fu
    default-encoding: UTF-8
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8

logging:
  config: classpath:logback-spring.xml

mybatis:
  config-location: classpath:mybatis-config.xml
