server:
  port: 8081
  context-path: /auth

security:
  oauth2:
    client:
      client-id: fuyongde
      client-secret: fuyongde
      access-token-uri: http://localhost:8081/auth/oauth/token
      token-name: access_token
      scope: read, write
    authorization:
      check-token-access: isAuthenticated()
  user:
    name: fuyongde
    password: fuyongde